### PR TITLE
Enemies speedup as time goes on

### LINKED ISSUE #68: Broken game mechanic
If you keep pressing space and either left or right arrow, it's almost impossible to lose :3

### PR DESCRIPTION
**Pull request by acheronfail**
This makes it so that the enemies will slowly increase speed as time goes on, making it slightly harder to get higher scores (otherwise the game can get boring pretty fast). 
The enemy speed resets each time the player dies.

This could potentially close #68 as well.

### CODE REVIEW

File: src/controllers/time.rs [hunk 1]
```diff
@@ -53,6 +53,7 @@ impl TimeController {
     /// `dt` is the amount of seconds that have passed since the last update
     pub fn update_seconds(&mut self, dt: f64, actions: &Actions, state: &mut GameState) {
         self.current_time += dt;
+        state.difficulty += 0.001;
```
Comment (aochagavia) [inline src/controllers/time.rs]: The increase in difficulty should depend on `dt`, which is the elapsed time since the last call to `update_seconds`. Otherwise the speed will increase faster when the game runs at a higher update rate.

Comment (acheronfail) [reply src/controllers/time.rs]: Good point, now it uses `dt`.

**Comment by aochagavia** [comment]
Great idea!
